### PR TITLE
Check for complete ruby_install_path before installing

### PR DESCRIPTION
**Pull request by krakatoa**
Hi benben, I made a little patch that aims for avoiding the ruby install step in case I set the install_dir flag to false. Thanks!

### CODE REVIEW

**Comment by benben** [comment]
Thanks for your PR! Actually I'm not sure what you want to archive with this. Why not just setting '$install_ruby` to false?

**Comment by krakatoa** [comment]
Hi Ben! let me tell you briefly my particular case,
I wanted to both set a specific Ruby version, with a subfolder that is different than the named version, in Puppet code:

  class {"rubybuild":
    ruby_version => "1.9.3-p484",
    ruby_install_dir => "/opt/rubies/ruby-1.9.3-p484"
  }

But, as I want the module to be in charge of the Ruby install AND keep this difference between version name and install path, I made the change I did, so I can now set version_in_dir to false and be sure Ruby gets installed only once.
Does it make any sense ?

thanks for your quick response!

**Comment by benben** [comment]
Ok thanks for clarification! Do you think it makes sense to add something to the readme for this?

**Comment by krakatoa** [comment]
Thanks benben, and sorry I forgot to respond your question ! I think the comment on the changelog makes sense :) (y)

**Comment by benben** [comment]
you're welcome! :beers:

**Pull request merged**
